server:
  port: 8001

spring:
  application:
    name: inventory-management-system
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://db-mysql-lon1-06524-do-user-22105866-0.e.db.ondigitalocean.com:25060/inventory-management-system
    username: "inventory-management-system"
    password: "AVNS_1tRdy9G5eUOOXvcX78m"
    hikari:
      initialization-fail-timeout: 0
  sql:
    int:
      platform: mysql
      mode: always
  jpa:
    databasePlatform: "org.hibernate.dialect.MySQLDialect"
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: clientId
            clientSecret: clientSecret
            scope: openid
            redirect-uri: http://standevpro.co.uk/login/oauth2/code/cognito
            clientName: clientName
        provider:
          cognito:
            issuerUri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_5MncTZem5
            user-name-attribute: cognito:username

      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_5MncTZem5


logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

springdoc:
  api-docs:
    path: /swagger-ui.html

#Spring Security with Cognito
uk:
  lset:
    service_url: http://standevpro.co.uk
    jwt:
      aws:
        userPoolId: us-east-1_5MncTZem5
        region: us-east-1
